# Generated by Django 3.1.6 on 2022-09-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='bloodgroup',
        ),
    ]
